### ISSUE TITLE
BOOTLOADER_BUTTON enabled in initial FOTA image

### ISSUE THREAD

**Issue by peterpan666** [ARMmbed/dfu-bootloader#5]
Hi @rgrover,

I've download the initial image here https://os.mbed.com/platforms/Nordic-nRF51-DK-FOTA/ but the bootloader button seems to be enabled, in this repo I can see [here](https://github.com/ARMmbed/nrf5x-dfu-bootloader/blob/master/main.c#L63) that it is disable.

Is this repo still relevant? Is it possible to have an initial image with the button disabled?

Thanks

**Comment by rgrover** [comment]
Hi @peterpan666, I am no longer active in mbed/BLE. Please contact the general forums. All the best.

**Comment by peterpan666** [comment]
Oh I see, thanks for the reply.
